GET http://localhost:8000/plan

###

POST  http://localhost:8000/plan/create
Content-Type: application/json

{
    "name" : "premiun",
    "describe" : "Plano ultilizado por todos",
    "users" : 24,
    "clients" : 150,
    "price" : "99.99",
    "type" : "anual"
}

###

PUT  http://localhost:8000/plan/
Content-Type: application/json

{
    "id": 1,
    "name" : "Padrão",
    "describe" : "Plano ultilizado por todos",
    "users" : 60,
    "clients" : 200,
    "price" : "120,59",
    "type" : "mensal"
}

###
