GET http://localhost:8000/request/1
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQ1MTk1NzM4LCJleHAiOjE3NDUyMjA5MzgsImRhdGEiOltdfQ.IEa5eOD-xHCBfOcn6xNBGr_UqyhBzHerW4naJAeqwgI

###

POST  http://localhost:8000/request/create
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQ1MTk1NzM4LCJleHAiOjE3NDUyMjA5MzgsImRhdGEiOltdfQ.IEa5eOD-xHCBfOcn6xNBGr_UqyhBzHerW4naJAeqwgI

{
    "client": 1,
    "title": "New Request",
    "describe": "This is a new request",
    "price": "198,00",
    "installments": 3,
    "fees": "10,00"

}

###

PUT http://localhost:8000/request/discard
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQ1MTk1NzM4LCJleHAiOjE3NDUyMjA5MzgsImRhdGEiOltdfQ.IEa5eOD-xHCBfOcn6xNBGr_UqyhBzHerW4naJAeqwgI

{
    "client": 1,
    "account": 2
}

###

PUT http://localhost:8000/request/accept
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQ1MTk1NzM4LCJleHAiOjE3NDUyMjA5MzgsImRhdGEiOltdfQ.IEa5eOD-xHCBfOcn6xNBGr_UqyhBzHerW4naJAeqwgI

{
    "client": 1,
    "account": 3
}

###

PUT http://localhost:8000/request/pay
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQ1MTk1NzM4LCJleHAiOjE3NDUyMjA5MzgsImRhdGEiOltdfQ.IEa5eOD-xHCBfOcn6xNBGr_UqyhBzHerW4naJAeqwgI

{
    "id": 1,
    "installments": 3
}

###
