GET http://localhost:8000/user

###

POST http://localhost:8000/user/login
Content-Type: application/json

{
    "email": "catedrau@gmail.com",
    "password": "111"
}

###

POST http://localhost:8000/user/register
Content-Type: application/json

{
    "name": "Avocate",
    "email": "catedrau@gmail.com",
    "password": "111",
    "cpf": "11322",
    "dateofbirth": "21/12/1910",
    "gender": "masc",
    "phone": "002001000",
    "position": "funcionario"
}
###

DELETE http://localhost:8000/user/delete/40668b33cba2eb66eaeda4f3fbe513b726b32ac99c007d65d6a331ee5d563507
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQzOTQyNjc2LCJleHAiOjE3NDM5Njc4NzYsImRhdGEiOltdfQ.JZ6ccrwcVzyJIt8GopgOyxKCrkkfV1vgC8Dy0cO7ln0

###

PUT http://localhost:8000/user/update
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQzOTQyNjc2LCJleHAiOjE3NDM5Njc4NzYsImRhdGEiOltdfQ.JZ6ccrwcVzyJIt8GopgOyxKCrkkfV1vgC8Dy0cO7ln0

{
    "hash": "40668b33cba2eb66eaeda4f3fbe513b726b32ac99c007d65d6a331ee5d563507",
    "name": "ba2cate",
    "email": "cat2ea@gmail.com",
    "password": "1211",
    "cpf": "12122",
    "dateofbirth": "21/12/1910",
    "gender": "masc",
    "phone": "000000000"
}

###

PATCH http://localhost:8000/user/active/bf515bf88fb9df00a0e224fc4f6a7b4f88010444e8d05615d58530e93b170fc3
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQzOTQyNjc2LCJleHAiOjE3NDM5Njc4NzYsImRhdGEiOltdfQ.JZ6ccrwcVzyJIt8GopgOyxKCrkkfV1vgC8Dy0cO7ln0

###

PATCH http://localhost:8000/user/forgoat
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQzOTQyNjc2LCJleHAiOjE3NDM5Njc4NzYsImRhdGEiOltdfQ.JZ6ccrwcVzyJIt8GopgOyxKCrkkfV1vgC8Dy0cO7ln0

{
    "user":"29b55714f046d82a8c8d2ad096b561aed5a8189128eda52865c10ee0b9b35338",
    "password": "1290"
}

###

GET http://localhost:8000/user/40668b33cba2eb66eaeda4f3fbe513b726b32ac99c007d65d6a331ee5d563507
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQzOTQyNjc2LCJleHAiOjE3NDM5Njc4NzYsImRhdGEiOltdfQ.JZ6ccrwcVzyJIt8GopgOyxKCrkkfV1vgC8Dy0cO7ln0

###

PATCH http://localhost:8000/user/join/00000009000000/dac83bb166491b2329888108d66e2b70df84e678f89ea98d71c9552ceb9f0907
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLmNvbSIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNzQ0NjYyNTU5LCJleHAiOjE3NDQ2ODc3NTksImRhdGEiOltdfQ.e8ZH0dap46Y78EH7klKjqsEctUZm5-X4uFlMbT32nyo

###
